### GET
GET http://localhost:1234/movies


### POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "Oppenheimer",
  "year" : 2023,
  "director": "Cristopher Nolan",
  "duration": 189,
  "rate": 8,
  "poster": "http://img.fruugo.com/oppenheimer.jpg",
  "genre": [
    "Drama",
    "Horror"
  ]
}
