### GET
GET http://localhost:1234/movies

### GET
GET http://localhost:1234/movies?genre=Action

### GET
GET http://localhost:1234/movies?genre=Biography


### POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "Barbie",
  "year" : 2023,
  "director": "Greta Gerwig",
  "duration": 114,
  "poster": "https://image.tmdb.org/t/p/original/9m9IkcHs7AmW9zS1Ly9ZOYxuKIE.jpg",
  "genre": [
    "Drama",
    "Comedy"
  ]
}

### PATCH
PATCH http://localhost:1234/movies/c5da9813-da73-4f65-b054-e41c3516ad5d
Content-Type: application/json

{
  "title": "Barbie extends"
}